# This file is machine-generated - editing it directly is not advised

[[NumericIO]]
deps = ["Printf"]
git-tree-sha1 = "5e2bd9bee8b55b754ca61386df207abbfc266ef6"
uuid = "6c575b1c-77cb-5640-a5dc-a54116c90507"
version = "0.3.2"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
