name = "ESeriesRounding"
uuid = "7b398af1-3c03-4c36-a68d-b29057ec0a45"
authors = ["KronosTheLate"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
