name = "ESeriesRounding"
uuid = "7b398af1-3c03-4c36-a68d-b29057ec0a45"
authors = ["KronosTheLate"]
version = "0.1.2"

[deps]
NumericIO = "6c575b1c-77cb-5640-a5dc-a54116c90507"

[compat]
NumericIO = "0.3.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
